plugins {
    id "groovy"
    id "java-library"
    id "io.micronaut.build.internal.toml-base"
    id "io.micronaut.build.internal.common"
}

dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor libs.micronaut.serde.processor

    api libs.micronaut.serde.api
    api libs.micronaut.serde.support
    api libs.micronaut.serde.processor
    api mn.micronaut.inject.java.test
    api mnTest.micronaut.test.spock
    api libs.jetbrains.annotations
    api mn.jackson.annotations

    compileOnly mn.micronaut.inject.groovy
}

tasks.named("spotlessGroovyCheck").configure { enabled = false }
tasks.named("spotlessJavaCheck").configure { enabled = false }
tasks.named("checkstyleMain").configure { enabled = false }
