pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    includeBuild 'jflex-plugin'
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.1'
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'toml-parent'

include 'toml-bom'
include 'toml'
include 'toml-serde'
include 'toml-serde-tck'
include 'doc-examples:example-toml-java'
include 'test-suite-toml-jackson-databind'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
}
