[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.0-M1"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.10"
spock = "2.3-groovy-4.0"

jetbrains-annotations = "23.0.0"
jflex = "1.8.2"
junit = "5.8.2"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jflex = { module = "de.jflex:jflex", version.ref = "jflex" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
