[versions]
micronaut-docs = "2.0.0"
micronaut = "4.8.7"
micronaut-test = "4.0.0"
groovy = "4.0.13"
spock = "2.3-groovy-4.0"

jetbrains-annotations = "26.0.2"
jflex = "1.9.1"
sonatype-scan = "3.0.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jflex = { module = "de.jflex:jflex", version.ref = "jflex" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
sonatype-scan = { module = "org.sonatype.gradle.plugins:scan-gradle-plugin", version.ref = "sonatype-scan" }
