[versions]
jetbrains-annotations = "16.0.3"
jflex = "1.8.2"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jflex = { module = "de.jflex:jflex", version.ref = "jflex" }
